// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDWcEbGJB-90amvmVYItvYOiJCBbZtwnY',
    appId: '1:313190035185:web:79e703b8728bd2c78d0350',
    messagingSenderId: '313190035185',
    projectId: 'bookapp-2d3f1',
    authDomain: 'bookapp-2d3f1.firebaseapp.com',
    storageBucket: 'bookapp-2d3f1.firebasestorage.app',
    measurementId: 'G-QB9DPFZHXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACeRkbnVEHUxIeNoS_oVGO19LMZqhnYa0',
    appId: '1:313190035185:android:41370c7dea4d02688d0350',
    messagingSenderId: '313190035185',
    projectId: 'bookapp-2d3f1',
    storageBucket: 'bookapp-2d3f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClYPEiimcBcMIrqskE_-SVkXYptDEmcoo',
    appId: '1:313190035185:ios:a0bb4d7e0bbaa8f48d0350',
    messagingSenderId: '313190035185',
    projectId: 'bookapp-2d3f1',
    storageBucket: 'bookapp-2d3f1.firebasestorage.app',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClYPEiimcBcMIrqskE_-SVkXYptDEmcoo',
    appId: '1:313190035185:ios:a0bb4d7e0bbaa8f48d0350',
    messagingSenderId: '313190035185',
    projectId: 'bookapp-2d3f1',
    storageBucket: 'bookapp-2d3f1.firebasestorage.app',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDWcEbGJB-90amvmVYItvYOiJCBbZtwnY',
    appId: '1:313190035185:web:a05d6ff082d9e30f8d0350',
    messagingSenderId: '313190035185',
    projectId: 'bookapp-2d3f1',
    authDomain: 'bookapp-2d3f1.firebaseapp.com',
    storageBucket: 'bookapp-2d3f1.firebasestorage.app',
    measurementId: 'G-N7EQBSEB75',
  );
}
